### ISSUE TITLE
Documenter le pipeline

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#78]
## Documentation

**Description:**

Documenter correctement et extensivement les procedures necessaires pour faire fonctionner le deploiement automatique dans le pipeline. Documenter les differentes extapes d'execution dans le workflow

**Scope:**

Wiki

**Task Details:**

Documentation complete

**Steps to Complete:**

Outline the steps required to complete this action item.

1. Documenter
2. Deployer
3. Profite

**Additional Information:**

S'assurer d'une documention de qualite pour que le projet puisse perdurer

## Checklist

- [x] I have provided clear and concise details for the documentation action item.
- [x] I have specified the scope or location in the documentation.
- [x] I have outlined the steps required to complete the task.
- [x] I have assigned the action item (if applicable).

**Comment by pabdelli** [comment]
Fait dans le rapport.
