### ISSUE TITLE
Mettre a jour - Readme + Wiki

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#81]
## Documentation

**Description:**

Mettre a jour le Readme et organiser les pages de la documentation Wiki

**Scope:**

NA

**Task Details:**

Na

**Steps to Complete:**

NA

**Additional Information:**

Include any additional context or information that might be relevant.

## Checklist

- [ ] I have provided clear and concise details for the documentation action item.
- [ ] I have specified the scope or location in the documentation.
- [ ] I have outlined the steps required to complete the task.
- [ ] I have assigned the action item (if applicable).

**Comment by pabdelli** [comment]
ReadMe manque toujours quelques details pour PyTransit. Serverless-API est ok ! Wiki ... pas fort.
