### ISSUE TITLE
Faire le Rapport Final

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#90]
## Documentation

**Description:**

Faire le rapport final du projet

**Scope:**

**Task Details:**

**Steps to Complete:**

**Additional Information:**

Include any additional context or information that might be relevant.

## Checklist

- [x] I have provided clear and concise details for the documentation action item.
- [x] I have specified the scope or location in the documentation.
- [x] I have outlined the steps required to complete the task.
- [x] I have assigned the action item (if applicable).

**Comment by SimonSt-Pierre** [comment]
UPDATE : 
* Squelette terminé;
* Toutes les sections sont incluses;
* Intro/conclusions/remerciements/recommandations presque terminés.
