### ISSUE TITLE
ReadMe Doc PyTransit

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#91]
## Documentation

**Description:**

Faire la documentation pour PyTransit ReadMe

**Scope:**

**Task Details:**

**Steps to Complete:**

**Additional Information:**

Include any additional context or information that might be relevant.

## Checklist

- [ ] I have provided clear and concise details for the documentation action item.
- [ ] I have specified the scope or location in the documentation.
- [ ] I have outlined the steps required to complete the task.
- [ ] I have assigned the action item (if applicable).
